TrainingMonitor/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using TrainingMonitor.Models;
using TrainingMonitor.Models.ViewModels;
using TrainingMonitor.Query;

namespace TrainingMonitor.Controllers
{
    public class BookingController : Controller
    {
        // GET: Booking
        public ActionResult Index()
        {
            var m = new BookingViewModel();
            using (var repo = new Repository())
            {
                m.Bookings = (from b in repo.BookingsByUser(User.Identity.GetUserId())
                    select new BookingModel
                    {
                        Id = b.Id,
                        DateTime = b.Datetime,
                        Duration = b.Duration,
                        Trainees = (from t in repo.TraineesByBooking(b.Id)
                                   select new TraineeModel
                                   {
                                       Id = t.Id,
                                       Firstname = t.Firstname,
                                       Surname = t.Surname,
                                       Avatar = t.Avatar,
                                       DateOfBirth = t.DateOfBirth,
                                       BeNumber = t.BeNumber
                                   }).ToList()
                    }).ToList();
                m.Trainees = (from t in repo.TraineesByUser(User.Identity.GetUserId())
                             select new TraineeModel
                             {
                                 Id = t.Id,
                                 Firstname = t.Firstname,
                                 Surname = t.Surname,
                                 Avatar = t.Avatar,
                                 DateOfBirth = t.DateOfBirth,
                                 BeNumber = t.BeNumber
                             }).ToList();
            }
            return View(m);
        }

        [HttpPost]
        public ActionResult Add(BookingModel m)
        {
            using (var repo = new Repository())
            {
                repo.AddBooking(m, User.Identity.GetUserId());
            }
            return RedirectToAction("Index");
        }
    }
}

TrainingMonitor/Controllers/TraineeController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using TrainingMonitor.Models;
using TrainingMonitor.Query;

namespace TrainingMonitor.Controllers
{
    [Authorize]
    public class TraineeController : Controller
    {
        // GET: Trainee
        public ActionResult Index()
        {
            using (var repo = new Repository())
            {
                var m = from t in repo.TraineesByUser(User.Identity.GetUserId())
                    select new TraineeModel
                    {
                        Id = t.Id,
                        Firstname = t.Firstname,
                        Surname = t.Surname,
                        Avatar = t.Avatar,
                        Description = "Ryan has been trained with me since 2015, he is a J3 player.",
                        DateOfBirth = t.DateOfBirth
                    };
                return View(m.ToList());
            }
        }

        [HttpPost]
        public ActionResult Add(TraineeModel m)
        {
            using (var repo = new Repository())
            {
                repo.AddTrainee(m, User.Identity.GetUserId());
            }
            return RedirectToAction("Index");
        }
    }
}

TrainingMonitor/Views/Shared/_Breadcrumb.cshtml
<div class="row m-l-10 m-r-10">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="btn-group">
                <ol class="breadcrumb hide-phone p-0 m-0">
                    @foreach (KeyValuePair<string, string> item in Model)
                    {
                        if (!string.IsNullOrEmpty(item.Value))
                        {
                            <li class="breadcrumb-item"><a href="@Url.Action(item.Value)">@item.Key</a></li>
                        }
                        else
                        {
                            <li class="breadcrumb-item active">@item.Key</li>
                        }
                    }
                </ol>
            </div>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

TrainingMonitor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Trainging Monitor</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- App favicon -->
    <link rel="shortcut icon" href="~/Content/images/favicon.ico">
    
    <!-- App css -->
    <link href="~\content/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~\content/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="~\content/css/style.css" rel="stylesheet" type="text/css" />
    <link href="~\content/css/Site.css" rel="stylesheet" type="text/css" />

    @*<script src="~\content/js/modernizr.min.js"></script>*@
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>
<header id="topnav">
    <div class="topbar-main">
        <div id="mainContainer" class="container">

            @*<div class="logo">
                <a href="\" class="logo">
                    <img src="~\content/images/logo_white_small.png" alt="" height="25" >
                </a>
            </div>*@

            <div class="navbar-custom">
                <div class="container">
                    <div id="navigation">
                        <ul id="topMenu" class="navigation-menu">
                            <li>@Html.ActionLink("My Trainees", "Index", "Trainee")</li>
                            <li>@Html.ActionLink("My Bookings", "Index", "Booking")</li>
                            <li>@Html.ActionLink("Upcoming Tournaments", "Index", "Tournaments")</li>
                            <li id="bigLogoItem" class="float-right">
                                <a href="\" class="logoBig">
                                    <img src="~\content/images/logo.png" alt="" height="60" >
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="menu-extras topbar-custom">
                <ul class="list-inline float-right mb-0">
                    <li class="menu-item list-inline-item">
                        <a class="navbar-toggle nav-link">
                            <div class="lines">
                                <span></span>
                                <span></span>
                                <span></span>
                            </div>
                        </a>
                    </li>
                </ul> 
            </div>
        </div>
    </div>
</header>
    
<div id="wrapper">
    <div class="container">
        @RenderBody()
    </div>
</div>


<script src="~/Content/js/jquery.min.js"></script>
<script src="~/Content/js/tether.min.js"></script>
<script src="~/Content/js/bootstrap.min.js"></script>
<script src="~/Content/js/metisMenu.min.js"></script>
<script src="~/Content/js/waves.js"></script>
<script src="~/Content/js/jquery.slimscroll.js"></script>

<!-- App js -->
<script src="~/Content/js/jquery.core.js"></script>
<script src="~/Content/js/jquery.app.js"></script>
    
@RenderSection("scripts", required: false)
</body>
</html>